In [1]:
## Numpy Array operations

In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9]);
print("Basic Slicing \n", arr[2:7]) #it gives the array index of 2->6
print("with step \n",arr[1:8:2]); # it gives the array index of 1->7 with the gap of 2

Basic Slicing 
 [3 4 5 6 7]
with step 
 [2 4 6 8]


In [11]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]]);
print("Specific element \n",arr_2d[1,2]) # it gives element of 1st row and 2nd column means ith row and jth column basically means arr[i][j] in java/c/c++
print("Entire row: \n", arr_2d[1]) #its gives the entire 1st row or the ith row
print("Entire column: \n", arr_2d[:,1]) #its gives entire 1st column or the jth column

Specific element 
 6
Entire row: 
 [4 5 6]
Entire column: 
 [2 5 8]


### Sorting

In [17]:
unsorted = np.array([3,1,4,1,5,9,2])
print("Sorted Array: \n",np.sort(unsorted)) #it gives you the sorted array

unsorted_2d = np.array([[3,1],
                        [2,3],
                        [4,5]]);
print("Sort 2D Array Column Wise: \n",np.sort(unsorted_2d, axis=0)) #it gives the sorted 2D array Column wise
print("Sorted 2D Array Row Wise: \n",np.sort(unsorted_2d,axis=1))#it gives the sorted 2D array Row wise

Sorted Array: 
 [1 1 2 3 4 5 9]
Sort 2D Array Column Wise: 
 [[2 1]
 [3 3]
 [4 5]]
Sorted 2D Array Row Wise: 
 [[1 3]
 [2 3]
 [4 5]]


### Filter Array

In [21]:
number = np.arange(1,11);
even_number = number[number%2==0] #its gives all even numbers
print("Even Numbers: ",even_number)

Even Numbers:  [ 2  4  6  8 10]


### Filter with mask

In [25]:
mask = number > 5;
print("Numbers greater than 5 ",number[mask]) #return numbers whic hare greater than 5

Numbers greater than 5  [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [30]:
print(number,"\n")
indices = [0,2,4]
print(number[indices]) #return indices of 0,2,4 values in numbers array

where_result = np.where(number>5)
print("\nIndices of elements in the numbers array who are greater than 5: \n",where_result);#it return indices of array which elements greater than 5
print("so the elements which are greater than 5:\n",number[where_result])#it return elements from the array which indices contains inside another array

[ 1  2  3  4  5  6  7  8  9 10] 

[1 3 5]

Indices of elements in the numbers array who are greater than 5: 
 (array([5, 6, 7, 8, 9]),)
so the elements which are greater than 5:
 [ 6  7  8  9 10]


In [32]:
condition_array = np.where(number>5,number*2,number)#it always tekes 2 conditions and check which indices greater than 5 and then multiply the elements of the indices by 2 and then return the elements of which indices that are inside the array
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### adding and removing data 

In [37]:
arr1 = np.array([1,2,3]);
arr2 = np.array([4,5,6]);
sum_array = arr1+arr2;#it add ith value with ith value
print("The sum array is: \n",sum_array)

combined_array = np.concatenate((arr1,arr2))
print("combined 2 arrays: \n",combined_array)#it combined two arrays

The sum array is: 
 [5 7 9]
combined 2 arrays: 
 [1 2 3 4 5 6]


### array compatibility

In [43]:
a = np.array([1,2,3]);
b = np.array([4,5,6]);
c = np.array([7,8,9,5]);

print("Compatibility Shapes: \n",a.shape==b.shape)#if both array contains same numbers of element return true else false
print("Compatibility Shapes: \n",a.shape==c.shape)

original = np.array([[1,2],[3,4]]);
new_row = np.array([5,6]);
with_new_row = np.vstack((original,new_row))#vstack -> vertical stack
print("Original array: \n",original)
print("new array: \n",with_new_row);

new_col = np.array([[7],[8]]);
with_new_col = np.hstack((original,new_col))#hstack -> horizontal stack
print("New Array: \n",with_new_col);

Compatibility Shapes: 
 True
Compatibility Shapes: 
 False
Original array: 
 [[1 2]
 [3 4]]
new array: 
 [[1 2]
 [3 4]
 [5 6]]
New Array: 
 [[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1,2,3,4,5]);
deleted = np.delete(arr,2);#delete element of index 2
print("Deleted array: \n",deleted)#it return new array without the element that you want to delete

Deleted array: 
 [1 2 4 5]
