In [6]:
import numpy as np;

In [2]:
### creating array from list

In [8]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d);

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d);

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


In [9]:
### List vs numpy array

In [11]:
py_list= [1,2,3]
print("python list multiplication ",py_list*2);

np_array= np.array([1,2,3]) #element wise multiplication
print("python array multiplication ",np_array*2);

python list multiplication  [1, 2, 3, 1, 2, 3]
python array multiplication  [2 4 6]


In [12]:
### creating array from scratch

In [15]:
zeros = np.zeros((3,4));
print("zeros array: \n", zeros);

ones = np.ones((2,2));
print("ones array: \n", ones);

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1.]
 [1. 1.]]


In [19]:
full = np.full((2,2), 7);
print("constant array: \n", full);
#random method
random = np.random.random((2,4))
print("random values: \n", random)

sequence = np.arange(0,10,2) #give numbers in sequence from 0->9 with 2 gap
print("sequence values: \n", sequence)

constant array: 
 [[7 7]
 [7 7]]
random values: 
 [[0.00523684 0.17886332 0.96923198 0.44378228]
 [0.47808922 0.64770079 0.98511427 0.28396   ]]
sequence values: 
 [0 2 4 6 8]


In [20]:
### Vector, Matrix and Tensor

In [26]:
vector = np.array([1,2,3]);
print("vector: \n",vector);

matrix = np.array([[1,2,3],[4,5,6]]);
print("matrix: \n",matrix);

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor: \n",tensor);

vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
### Array Properties

In [31]:
arr = np.array([[1,2,3],
                [4,5,6]]);
print("shape of ",arr.shape); # it's gives number of rows & column
print("Dimention: ",arr.ndim) # it's gives number of dimentions
print("Size: ",arr.size)# it's gives size of the array-> total number of elements
print("data type: ",arr.dtype)#it's gives data type 

shape of  (2, 3)
Dimention:  2
Size:  6
data type:  int64


In [32]:
### Array Reshaping

In [ ]:
arr = np.arange(12);# gives sequence of values from 0->11
print("Original Array",arr);
reshaped = arr.reshape((3,4))
print("\nReshaped Array: \n",reshaped) # its gives the array of 3 rows and 4 columns

flattend = reshaped.flatten()
print("\n Flattend Array: \n",flattend)#it's gives the array in flat and try to give a 1D array

# ravel (return view, instade of copy)->means return the original array
raveled = reshaped.ravel()
print("\n Raveled Array: \n", raveled) #it's also gives you a falt array and try to give a 1D array

transpose = reshaped.T #its gives the transposed of a matrix and it isn't a method it is a property of array
print("\n transposed array is: \n", transpose)

Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattend Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transposed array is: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
